import {
  LayoutDashboard,
  Package,
  Truck,
  BarChart3,
  Megaphone,
  MessageSquare,
  Users,
  Settings,
  ShoppingCart,
  Grid3X3,
  FlaskConical,
  Factory,
  Warehouse,
  Ship,
  CreditCard,
  LineChart,
  PieChart,
  TrendingUp,
  Calculator,
  UserCheck,
  Camera,
  Calendar,
  DollarSign,
  Star,
  Building2,
  BookOpen,
  Lightbulb,
  Handshake,
  Bot,
  Plug,
  Radio,
  ShieldCheck,
} from "lucide-react"
import type { NavGroup } from "@/types/navigation"

export const navigationGroups: NavGroup[] = [
  {
    id: "home",
    icon: LayoutDashboard,
    label: "Главная",
    items: [
      { id: "dashboard", label: "Дашборд", icon: LayoutDashboard, path: "/dashboard" },
    ],
  },
  {
    id: "product",
    icon: Package,
    label: "Продукт",
    items: [
      { id: "catalog", label: "Каталог", icon: ShoppingCart, path: "/product/catalog" },
      { id: "matrix", label: "Товарная матрица", icon: Grid3X3, path: "/product/matrix" },
      { id: "development", label: "Разработки", icon: FlaskConical, path: "/product/development", badge: "канбан" },
      { id: "production", label: "Производство", icon: Factory, path: "/product/production", badge: "канбан" },
    ],
  },
  {
    id: "operations",
    icon: Truck,
    label: "Операции",
    items: [
      { id: "warehouse", label: "Склад", icon: Warehouse, path: "/operations/warehouse" },
      { id: "supply", label: "План поставок", icon: Calculator, path: "/operations/supply" },
      { id: "shipments", label: "Поставки", icon: Ship, path: "/operations/shipments", badge: "канбан" },
      { id: "finance", label: "Финансы", icon: CreditCard, path: "/operations/finance" },
    ],
  },
  {
    id: "analytics",
    icon: BarChart3,
    label: "Аналитика",
    items: [
      { id: "overview", label: "Сводка", icon: LineChart, path: "/analytics/overview" },
      { id: "abc", label: "ABC-анализ", icon: PieChart, path: "/analytics/abc" },
      { id: "promo", label: "Продвижение", icon: TrendingUp, path: "/analytics/promo" },
      { id: "unit", label: "Юнит-экономика", icon: Calculator, path: "/analytics/unit" },
    ],
  },
  {
    id: "marketing",
    icon: Megaphone,
    label: "Маркетинг",
    items: [
      { id: "influencer", label: "Influencer CRM", icon: UserCheck, path: "/marketing/influencer" },
      { id: "ugc", label: "UGC-креаторы", icon: Camera, path: "/marketing/ugc" },
      { id: "smm", label: "SMM-планер", icon: Calendar, path: "/marketing/smm" },
      { id: "pricing", label: "Ценообразование", icon: DollarSign, path: "/marketing/pricing" },
    ],
  },
  {
    id: "comms",
    icon: MessageSquare,
    label: "Коммуникации",
    items: [
      { id: "comms-dashboard", label: "Дашборд", icon: LayoutDashboard, path: "/comms/dashboard" },
      { id: "reviews", label: "Отзывы и ответы", icon: Star, path: "/comms/reviews" },
      { id: "store-settings", label: "Настройки магазинов", icon: Settings, path: "/comms/store-settings" },
      { id: "comms-analytics", label: "Аналитика", icon: BarChart3, path: "/comms/analytics" },
      { id: "comms-broadcasts", label: "Рассылки", icon: Radio, path: "/comms/broadcasts" },
    ],
  },
  {
    id: "team",
    icon: Users,
    label: "Команда",
    items: [
      { id: "employees", label: "Сотрудники", icon: Users, path: "/team/employees" },
      { id: "org", label: "Оргструктура", icon: Building2, path: "/team/org" },
      { id: "knowledge", label: "База знаний", icon: BookOpen, path: "/team/knowledge" },
      { id: "ideas", label: "Гипотезы и идеи", icon: Lightbulb, path: "/team/ideas", badge: "канбан" },
      { id: "contractors", label: "Подрядчики", icon: Handshake, path: "/team/contractors" },
    ],
  },
  {
    id: "system",
    icon: Settings,
    label: "Система",
    items: [
      { id: "settings", label: "Настройки", icon: Settings, path: "/system/settings" },
      { id: "agents", label: "Агенты", icon: Bot, path: "/system/agents" },
      { id: "integrations", label: "Интеграции", icon: Plug, path: "/system/integrations" },
      { id: "matrix-admin", label: "Matrix Admin", icon: ShieldCheck, path: "/system/matrix-admin" },
    ],
  },
]
