"""Base signal patterns — seeded into kb_patterns with source_tag='base'."""
from __future__ import annotations

BASE_PATTERNS: list[dict] = [
    # === 5 рычагов маржи ===
    {
        "pattern_name": "margin_lags_orders",
        "description": "Заказы растут быстрее маржи (разрыв > 5 п.п.)",
        "category": "margin",
        "trigger_condition": {"metric_pair": ["orders_completion_pct", "margin_completion_pct"], "operator": "gap_gt", "threshold": 5},
        "action_hint": "Проверить, какие модели дают рост заказов. Если низкомаржинальные — перераспределить рекламу",
        "impact_on": "margin",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "spp_shift_up",
        "description": "СПП выросла > 2 п.п. — можно поднять базовую цену",
        "category": "price",
        "trigger_condition": {"metric": "spp_delta_pp", "operator": ">", "threshold": 2},
        "action_hint": "Для A-группы (стратегия Маржа): поднять базовую цену. Для Growth: оставить, ловить долю рынка",
        "impact_on": "margin",
        "severity": "info",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "spp_shift_down",
        "description": "СПП упала > 2 п.п. — клиентская цена выросла, конверсия под угрозой",
        "category": "price",
        "trigger_condition": {"metric": "spp_delta_pp", "operator": "<", "threshold": -2},
        "action_hint": "Рассмотреть снижение базовой цены для сохранения клиентской цены и спроса",
        "impact_on": "both",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "adv_overspend",
        "description": "ДРР выше нормы (>12% WB, >18% Ozon внутр.)",
        "category": "adv",
        "trigger_condition": {"metric": "drr_internal_pct", "operator": ">", "threshold": 12, "scope": "channel"},
        "action_hint": "Оптимизировать ключевые слова, снизить ставки на низкоконверсионных, проверить ROMI по кампаниям",
        "impact_on": "margin",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "adv_underspend",
        "description": "ДРР ниже нормы, но заказы не растут — мало трафика",
        "category": "adv",
        "trigger_condition": {"metric": "drr_internal_pct", "operator": "<", "threshold": 5, "and": {"metric": "orders_growth_pct", "operator": "<", "threshold": 0}},
        "action_hint": "Увеличить рекламный бюджет, расширить семантику",
        "impact_on": "both",
        "severity": "info",
        "source_tag": "base",
        "confidence": "medium",
    },
    {
        "pattern_name": "logistics_overweight",
        "description": "Логистика > 8% от выручки",
        "category": "margin",
        "trigger_condition": {"metric": "logistics_share_pct", "operator": ">", "threshold": 8},
        "action_hint": "Проверить индекс локализации (WB), сроки доставки (Ozon), уровень возвратов",
        "impact_on": "margin",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "cogs_anomaly",
        "description": "Себестоимость отклонилась > 5% от нормы (~350 руб)",
        "category": "margin",
        "trigger_condition": {"metric": "cogs_deviation_pct", "operator": ">", "threshold": 5},
        "action_hint": "Проверить поставщика, микс артикулов",
        "impact_on": "margin",
        "severity": "critical",
        "source_tag": "base",
        "confidence": "high",
    },
    # === Воронка ===
    {
        "pattern_name": "ctr_drop",
        "description": "CTR < 2% (WB) или < 1.5% (Ozon)",
        "category": "funnel",
        "trigger_condition": {"metric": "ctr_pct", "operator": "<", "threshold": 2, "scope": "channel"},
        "action_hint": "Обновить главное фото, проверить ценовую конкурентоспособность, войти в акцию МП",
        "impact_on": "both",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "cart_to_order_drop",
        "description": "CR корзина-заказ упал > 5 п.п. WoW",
        "category": "funnel",
        "trigger_condition": {"metric": "cart_to_order_delta_pp", "operator": "<", "threshold": -5},
        "action_hint": "Проверить: цена изменилась? размеры в наличии? сроки доставки? конкуренты?",
        "impact_on": "both",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "cro_improvement",
        "description": "Сквозная конверсия переход-заказ выросла",
        "category": "funnel",
        "trigger_condition": {"metric": "cro_delta_pp", "operator": ">", "threshold": 0.5},
        "action_hint": "Позитивный сигнал. Больше заказов с того же трафика = ДРР снижается",
        "impact_on": "both",
        "severity": "info",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "sales_lag_expected",
        "description": "Заказы растут значительно, продажи слабо — лаг выкупов",
        "category": "funnel",
        "trigger_condition": {"metric_pair": ["orders_growth_pct", "sales_growth_pct"], "operator": "gap_gt", "threshold": 8},
        "action_hint": "Не тревога. Продажи подтянутся через 5-10 дней. Мониторить",
        "impact_on": "turnover",
        "severity": "info",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "sales_lag_problem",
        "description": "Заказы растут, продажи падают — возвраты или отмены",
        "category": "funnel",
        "trigger_condition": {"and": [
            {"metric": "orders_growth_pct", "operator": ">", "threshold": 5},
            {"metric": "sales_growth_pct", "operator": "<", "threshold": -5},
        ]},
        "action_hint": "Проверить причины возвратов/отмен: качество, соответствие описанию, размерная сетка",
        "impact_on": "both",
        "severity": "critical",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "buyout_drop",
        "description": "Выкуп < 45% WB или < 30% Ozon",
        "category": "funnel",
        "trigger_condition": {"metric": "buyout_pct", "operator": "<", "threshold": 45, "scope": "channel"},
        "action_hint": "Анализировать: доставка, соответствие фото/описанию, качество, размерная сетка",
        "impact_on": "both",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "medium",
    },
    # === Реклама ===
    {
        "pattern_name": "romi_critical",
        "description": "ROMI < 50% — реклама глубоко убыточна",
        "category": "adv",
        "trigger_condition": {"metric": "romi_pct", "operator": "<", "threshold": 50},
        "action_hint": "СТОП реклама, переход на органику. Исключение: новые модели < 4 нед.",
        "impact_on": "margin",
        "severity": "critical",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "cac_exceeds_profit",
        "description": "CAC > маржа на единицу — каждый заказ убыточен",
        "category": "adv",
        "trigger_condition": {"metric_pair": ["cac_rub", "margin_per_unit_rub"], "operator": "a_gt_b"},
        "action_hint": "Снизить ставки или остановить рекламу на этом артикуле",
        "impact_on": "margin",
        "severity": "critical",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "keyword_drain",
        "description": "Ключевое слово: много трафика, 0 заказов — пустышка",
        "category": "adv",
        "trigger_condition": {"metric": "keyword_orders", "operator": "==", "threshold": 0, "and": {"metric": "keyword_clicks", "operator": ">", "threshold": 50}},
        "action_hint": "Добавить в минус-слова или снизить ставку",
        "impact_on": "margin",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "organic_declining",
        "description": "Доля органики упала > 5 п.п. WoW — зависимость от рекламы растёт",
        "category": "adv",
        "trigger_condition": {"metric": "organic_share_delta_pp", "operator": "<", "threshold": -5},
        "action_hint": "Проверить позиции по ключевым запросам, новых конкурентов, изменения алгоритма WB",
        "impact_on": "both",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "medium",
    },
    {
        "pattern_name": "ad_no_organic_growth",
        "description": "Рекламируем, но органика не растёт — проблема с карточкой",
        "category": "adv",
        "trigger_condition": {"and": [
            {"metric": "adv_spend_growth_pct", "operator": ">", "threshold": 10},
            {"metric": "organic_share_delta_pp", "operator": "<", "threshold": 0},
        ]},
        "action_hint": "Проверить карточку: релевантность запросам, фото, описание, отзывы",
        "impact_on": "both",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "medium",
    },
    # === Оборачиваемость + ABC ===
    {
        "pattern_name": "low_roi_article",
        "description": "ABC=C + маржа <15% + оборачиваемость > 1.5x медианы — кандидат на вывод",
        "category": "turnover",
        "trigger_condition": {"and": [
            {"metric": "abc_class", "operator": "==", "threshold": "C"},
            {"metric": "margin_pct", "operator": "<", "threshold": 15},
            {"metric": "turnover_ratio", "operator": ">", "threshold": 1.5},
        ]},
        "action_hint": "Кандидат на вывод. Проверить: можно ли снизить цену для ликвидации?",
        "impact_on": "turnover",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "high_roi_opportunity",
        "description": "Быстрая оборачиваемость + маржа > 25% — масштабировать",
        "category": "turnover",
        "trigger_condition": {"and": [
            {"metric": "margin_pct", "operator": ">", "threshold": 25},
            {"metric": "turnover_ratio", "operator": "<", "threshold": 0.8},
        ]},
        "action_hint": "Увеличить запас, нарастить рекламу, расширить размерный ряд",
        "impact_on": "both",
        "severity": "info",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "big_inefficient",
        "description": "ABC=A/B + маржа < 10% — большой, но неэффективный",
        "category": "model",
        "trigger_condition": {"and": [
            {"metric": "abc_class", "operator": "in", "threshold": ["A", "B"]},
            {"metric": "margin_pct", "operator": "<", "threshold": 10},
        ]},
        "action_hint": "Пересмотреть ценообразование. Проверить: можно ли поднять цену без потери объёма?",
        "impact_on": "margin",
        "severity": "warning",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "status_mismatch",
        "description": "Статус 'Выводим' + ABC=A/B + маржа > 15% — ошибка статуса",
        "category": "model",
        "trigger_condition": {"and": [
            {"metric": "status", "operator": "==", "threshold": "withdrawing"},
            {"metric": "abc_class", "operator": "in", "threshold": ["A", "B"]},
            {"metric": "margin_pct", "operator": ">", "threshold": 15},
        ]},
        "action_hint": "Проверить причину вывода. Если нет веской причины — вернуть в продажу",
        "impact_on": "both",
        "severity": "critical",
        "source_tag": "base",
        "confidence": "high",
    },
    # === Ценовые ===
    {
        "pattern_name": "price_signal",
        "description": "Ср. чек заказов != ср. чек продаж (> 5%) — прогноз выручки",
        "category": "price",
        "trigger_condition": {"metric_pair": ["avg_order_price", "avg_sale_price"], "operator": "gap_pct_gt", "threshold": 5},
        "action_hint": "Если чек заказов > чек продаж — выручка вырастет через 3-7 дней. Наоборот — упадёт",
        "impact_on": "margin",
        "severity": "info",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "margin_pct_drop",
        "description": "Маржинальность % падает при росте выручки — рост неэффективен",
        "category": "margin",
        "trigger_condition": {"and": [
            {"metric": "revenue_growth_pct", "operator": ">", "threshold": 10},
            {"metric": "margin_completion_pct", "operator": "<", "threshold": 100},
        ]},
        "action_hint": "Проверить 5 рычагов маржи: цена, СПП, ДРР, логистика, себестоимость",
        "impact_on": "margin",
        "severity": "critical",
        "source_tag": "base",
        "confidence": "high",
    },
    {
        "pattern_name": "price_up_rank_risk",
        "description": "Цена поднята — риск потери позиций и роста ДРР",
        "category": "price",
        "trigger_condition": {"metric": "price_change_pct", "operator": ">", "threshold": 3},
        "action_hint": "Мониторить: позиции, конверсию, ДРР на следующий день. Если конверсия упала > 10% — откатить",
        "impact_on": "both",
        "severity": "info",
        "source_tag": "base",
        "confidence": "medium",
    },
]
