-- =============================================================
-- BACKUP DDL + DATA — dropped tables (2026-04-06)
-- Audit remediation: Wave 3 cleanup
-- =============================================================

-- =====================
-- SCHEMA: assistant (all tables empty, 0 rows)
-- =====================

CREATE SCHEMA IF NOT EXISTS assistant;

CREATE TABLE assistant.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  telegram_id bigint NOT NULL,
  telegram_chat_id bigint NOT NULL,
  bitrix_user_id bigint NOT NULL,
  email text NOT NULL,
  timezone text NOT NULL DEFAULT 'Europe/Moscow'::text,
  notifications_enabled boolean NOT NULL DEFAULT true,
  morning_time time without time zone NOT NULL DEFAULT '08:00:00'::time without time zone,
  evening_time time without time zone NOT NULL DEFAULT '18:00:00'::time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id),
  UNIQUE (telegram_id),
  UNIQUE (email)
);

CREATE TABLE assistant.auth_codes (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  telegram_id bigint NOT NULL,
  email text NOT NULL,
  code_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts smallint NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE assistant.tasks_cache (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  bitrix_task_id bigint NOT NULL UNIQUE,
  bitrix_user_id bigint NOT NULL,
  title text NOT NULL,
  status text NOT NULL,
  deadline timestamp with time zone,
  updated_at timestamp with time zone,
  raw_payload jsonb,
  PRIMARY KEY (id)
);

CREATE TABLE assistant.events_cache (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  bitrix_event_id bigint NOT NULL UNIQUE,
  bitrix_user_id bigint NOT NULL,
  title text NOT NULL,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone,
  raw_payload jsonb,
  PRIMARY KEY (id)
);

CREATE TABLE assistant.sync_state (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  bitrix_user_id bigint NOT NULL,
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['task', 'event', 'user'])),
  last_synced_at timestamp with time zone,
  PRIMARY KEY (id),
  UNIQUE (bitrix_user_id, entity_type)
);

CREATE TABLE assistant.notification_outbox (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dedupe_key text NOT NULL UNIQUE,
  telegram_chat_id bigint NOT NULL,
  payload jsonb NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_deadline ON assistant.tasks_cache(deadline);
CREATE INDEX IF NOT EXISTS idx_events_start ON assistant.events_cache(start_at);
CREATE INDEX IF NOT EXISTS idx_sync_state_user ON assistant.sync_state(bitrix_user_id);

-- =====================
-- TABLES: lyudmila_*
-- =====================

CREATE TABLE public.lyudmila_employees (
  id serial PRIMARY KEY,
  bitrix_id integer NOT NULL UNIQUE,
  first_name text,
  last_name text,
  full_name text,
  email text,
  position text,
  department_ids integer[] DEFAULT '{}',
  is_internal boolean DEFAULT false,
  is_active boolean DEFAULT true,
  custom_role text,
  synced_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.lyudmila_tasks (
  id serial PRIMARY KEY,
  bitrix_task_id integer NOT NULL UNIQUE,
  title text,
  description text,
  status integer,
  priority integer,
  responsible_id integer,
  created_by integer,
  deadline timestamp with time zone,
  created_at timestamp with time zone,
  closed_at timestamp with time zone,
  auditors integer[] DEFAULT '{}',
  accomplices integer[] DEFAULT '{}',
  synced_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.lyudmila_task_comments (
  id serial PRIMARY KEY,
  bitrix_task_id integer NOT NULL,
  author_id integer,
  comment_text text,
  created_at timestamp with time zone,
  synced_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.lyudmila_suggestions (
  id serial PRIMARY KEY,
  telegram_id bigint NOT NULL,
  entity_type text NOT NULL,
  suggestion_text text NOT NULL,
  suggestion_type text,
  accepted boolean,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.lyudmila_user_preferences (
  id serial PRIMARY KEY,
  telegram_id bigint NOT NULL,
  preference_key text NOT NULL,
  preference_value text NOT NULL,
  confidence real DEFAULT 0.5,
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE (telegram_id, preference_key)
);

CREATE INDEX IF NOT EXISTS idx_lyudmila_employees_bitrix_id ON public.lyudmila_employees(bitrix_id);
CREATE INDEX IF NOT EXISTS idx_lyudmila_employees_internal ON public.lyudmila_employees(is_internal);
CREATE INDEX IF NOT EXISTS idx_lyudmila_tasks_bitrix_id ON public.lyudmila_tasks(bitrix_task_id);
CREATE INDEX IF NOT EXISTS idx_lyudmila_tasks_responsible ON public.lyudmila_tasks(responsible_id);
CREATE INDEX IF NOT EXISTS idx_lyudmila_tasks_created_by ON public.lyudmila_tasks(created_by);
CREATE INDEX IF NOT EXISTS idx_lyudmila_tasks_deadline ON public.lyudmila_tasks(deadline);
CREATE INDEX IF NOT EXISTS idx_lyudmila_tasks_status ON public.lyudmila_tasks(status);
CREATE INDEX IF NOT EXISTS idx_lyudmila_comments_task ON public.lyudmila_task_comments(bitrix_task_id);
CREATE INDEX IF NOT EXISTS idx_lyudmila_comments_author ON public.lyudmila_task_comments(author_id);
CREATE INDEX IF NOT EXISTS idx_lyudmila_suggestions_tg ON public.lyudmila_suggestions(telegram_id);
CREATE INDEX IF NOT EXISTS idx_lyudmila_prefs_tg ON public.lyudmila_user_preferences(telegram_id);

-- =====================
-- DATA BACKUP: lyudmila_employees (22 rows)
-- =====================

INSERT INTO lyudmila_employees (id, bitrix_id, first_name, last_name, full_name, email, position, department_ids, is_internal, is_active, custom_role, synced_at) VALUES
(1, 1, 'Данила', 'Матвеев', 'Данила Матвеев', 'matveev@wookiee.shop', 'Генеральный директор ', '{1,3,5,25,9,21,23,27,11,7,17}', true, true, NULL, '2026-02-15T01:11:27.922007+00:00'),
(2, 11, 'Валерия', 'Матвеева', 'Валерия Матвеева', 'matveeva@wookiee.shop', 'Офис менеджер, бизнес ассистент, менеджер блогеров', '{3}', true, true, NULL, '2026-02-15T01:11:28.043069+00:00'),
(3, 13, 'Евгения', 'Сек', 'Евгения Сек', 'sek@wookiee.shop', 'Менеджер склада и проверки качества', '{27}', true, true, NULL, '2026-02-15T01:11:28.152121+00:00'),
(4, 17, 'Дмитрий', 'Дрозд', 'Дмитрий Дрозд', 'drozd@wookiee.shop', 'Руководитель склада / менеджер закупки', '{27}', true, true, NULL, '2026-02-15T01:11:28.260013+00:00'),
(5, 19, 'Мария', 'Делова', 'Мария Делова', 'delova@wookiee.shop', 'Проджект SMM', '{23}', true, true, NULL, '2026-02-15T01:11:28.368117+00:00'),
(6, 25, 'Полина', 'Медведева', 'Полина Медведева', 'medvedeva@wookiee.shop', 'Директор по продукту', '{11}', true, true, NULL, '2026-02-15T01:11:28.478679+00:00'),
(7, 41, 'Светлана', 'Корабец', 'Светлана Корабец', 'korabets@wookiee.shop', 'Менеджер по рекламе', '{7}', true, true, NULL, '2026-02-15T01:11:28.587102+00:00'),
(8, 51, 'Дарина', 'Сапронова', 'Дарина Сапронова', 'darinasapronova@gmail.com', '', '{}', false, true, NULL, '2026-02-15T01:11:28.700079+00:00'),
(9, 61, 'Артём', 'Портнов', 'Артём Портнов', 'info@portnovlab.ru', '', '{25}', false, true, NULL, '2026-02-15T01:11:28.832175+00:00'),
(10, 327, 'SKEYLO -', 'Юридические вопросы', 'SKEYLO - Юридические вопросы', 'polyak0vaalina@yandex.ru', 'Юрист', '{29}', false, true, NULL, '2026-02-15T01:11:28.939993+00:00'),
(11, 463, 'Виктор', 'Чебан', 'Виктор Чебан', 'v@portnovlab.ru', '', '{25}', false, true, NULL, '2026-02-15T01:11:29.0512+00:00'),
(12, 473, 'Ирина', 'Дмитриева', 'Ирина Дмитриева', 'dmitrieva@wookiee.shop', 'Операционный менеджер', '{5}', true, true, NULL, '2026-02-15T01:11:29.160091+00:00'),
(13, 555, 'Алина', 'Кантеева', 'Алина Кантеева', 'kanteyeva@wookiee.shop', 'Контент менеджер', '{17}', true, true, NULL, '2026-02-15T01:11:29.269022+00:00'),
(14, 613, 'Элина', 'Авдеева', 'Элина Авдеева', 'avdeeva@wookiee.shop', 'Категорийный менеджер / продукт менеджер', '{11}', true, true, NULL, '2026-02-15T01:11:29.376906+00:00'),
(15, 699, 'Salmon', 'IT', 'Salmon IT', 'salmon.it@yandex.ru', '', '{1}', false, true, NULL, '2026-02-15T01:11:29.485103+00:00'),
(16, 707, 'Татьяна', 'Матвеева', 'Татьяна Матвеева', '', 'менеджер склада, сборщик', '{1}', false, true, NULL, '2026-02-15T01:11:29.593005+00:00'),
(17, 719, 'Пустой', 'Аккаунт', 'Пустой Аккаунт', 'reg@wookiee.shop', '', '{1}', true, true, NULL, '2026-02-15T01:11:29.704193+00:00'),
(18, 839, 'Александра', 'Леховицкая', 'Александра Леховицкая', 'lehovitskaya@gmail.com', 'HR Консультант', '{1}', false, true, NULL, '2026-02-15T01:11:29.877122+00:00'),
(19, 1057, 'Анастасия', 'Лигус', 'Анастасия Лигус', 'ligus@wookiee.shop', 'Менеджер маркетплейсов', '{1}', true, true, NULL, '2026-02-15T01:11:29.9852+00:00'),
(20, 1315, 'Галия', 'Талипова', 'Галия Талипова', 'Buhfin.gg@gmail.com', 'Бухгалтер', '{1}', false, true, NULL, '2026-02-15T01:11:30.121093+00:00'),
(21, 1435, 'Артем', 'Колчин', 'Артем Колчин', 'kolchin@wookiee.shop', 'Финансовый менеджер', '{1}', true, true, NULL, '2026-02-15T01:11:30.277043+00:00'),
(22, 1625, 'Алина', 'Сотникова', 'Алина Сотникова', 'sotnikova@wookiee.shop', 'Категорийный менеджер, менеджер по закупкам в китае', '{1}', true, true, NULL, '2026-02-15T01:11:30.476084+00:00');

-- =====================
-- DATA NOTE: lyudmila_tasks (5220 rows)
-- Source: Bitrix24 sync (bitrix_task_id). Can be re-synced from Bitrix if needed.
-- Data not included due to volume (~600KB per 500 rows).
-- task_comments: 0 rows, suggestions: 0 rows, user_preferences: 0 rows
-- =====================
